# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: desktop:build

    - name: list0
      run: ls
      run: cd dekstop
      run: ls
      run: cd build
      run: ls
      run: cd libs
      run: ls

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%m.%d')"

    - name: Show date
      run: echo $DATE_VAL
      env:
        DATE_VAL: ${{ steps.date.outputs.date }}

    - name: Rename build file.
      run: mv ./desktop/build/libs/desktop-1.0.jar paintbots_0.$DATE_VAL.jar
      env:
        DATE_VAL: ${{ steps.date.outputs.date }}

    - name: List files
      run: echo ls ./desktop/build/libs/
